"""
porter/emitters/aider.py — Emitter for Aider coding agent environments.
Generates CONVENTIONS.md, .aider.conf.yml and a verbatim `.aider/` support tree.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Tuple

from porter.emitters.common import Plan, commit, index_section, plan_support_tree
from porter.models import UniversalManifest
from porter.sanitizer import ConstitutionalSanitizer


class AiderEmitter:
    """Exports Antigravity Harness for Aider environments."""

    TARGET = "aider"
    SKILLS_DIR = ".aider/skills"
    AGENTS_DIR = ".aider/agents"

    @classmethod
    def plan(cls, manifest: UniversalManifest, output_dir: Path) -> Tuple[Plan, Dict[Path, str]]:
        plan, links = plan_support_tree(manifest, output_dir / cls.SKILLS_DIR, output_dir / cls.AGENTS_DIR)
        const = ConstitutionalSanitizer.sanitize_for_export(manifest.constitution.get("raw", ""), target=cls.TARGET)
        design = ConstitutionalSanitizer.sanitize_for_export(manifest.design_contract.get("raw", ""), target=cls.TARGET)
        plan[output_dir / "CONVENTIONS.md"] = f"""# Project Conventions & Engineering Rules

> Exported from Antigravity Harness v{manifest.version}. Add a skill to the chat with
> `/read {cls.SKILLS_DIR}/<name>/SKILL.md` when it applies.

{const}

---

## Design Contract & Quality Standards

{design}

---

{index_section(manifest, cls.SKILLS_DIR, cls.AGENTS_DIR)}
"""
        plan[output_dir / ".aider.conf.yml"] = """# Aider configuration generated by Antigravity Porter
read:
  - CONVENTIONS.md
auto-commits: false
stream: false
"""
        return plan, links

    @classmethod
    def emit(cls, manifest: UniversalManifest, output_dir: Path, force: bool = False) -> List[Path]:
        plan, links = cls.plan(manifest, Path(output_dir))
        return commit(plan, links, force=force)
