"""
porter/emitters/aider.py — Emitter for Aider coding agent environments.
Generates CONVENTIONS.md and .aider.conf.yml configuration.
"""

from __future__ import annotations

from pathlib import Path
from typing import List
from porter.models import UniversalManifest
from porter.sanitizer import ConstitutionalSanitizer


class AiderEmitter:
    """Exports Antigravity Harness for Aider environments."""

    @classmethod
    def emit(cls, manifest: UniversalManifest, output_dir: Path) -> List[Path]:
        output_dir.mkdir(parents=True, exist_ok=True)
        emitted = []

        conventions_path = output_dir / "CONVENTIONS.md"
        const_raw = manifest.constitution.get("raw", "")
        sanitized = ConstitutionalSanitizer.sanitize_for_export(const_raw, target="aider")

        conventions_path.write_text(f"""# Project Conventions & Engineering Rules

> Exported from Antigravity Harness v{manifest.version}

{sanitized}
""", encoding="utf-8")
        emitted.append(conventions_path)

        # .aider.conf.yml
        aider_conf_path = output_dir / ".aider.conf.yml"
        aider_conf = f"""# Aider configuration generated by Antigravity Porter
read:
  - CONVENTIONS.md
auto-commits: false
stream: false
"""
        aider_conf_path.write_text(aider_conf, encoding="utf-8")
        emitted.append(aider_conf_path)

        return emitted
